#!/usr/bin/env python
from __future__ import print_function
import sys
import re
import os

REPO_DIR = "/opt/mtanalyze"
TRY_DIR = "/opt/git/mtanalyze"
if os.path.isfile(os.path.join(TRY_DIR, "mtanalyze", "__init__.py")):
    REPO_DIR = TRY_DIR
elif not os.path.isfile(os.path.join(REPO_DIR, "mtanalyze", "__init__.py")):
    raise FileNotFoundError(
        "You must first do:\n  git clone https://github.com/poikilos/mtanalyze.git {repo_dir}"
        " && sudo chown minebest:minebest -r {repo_dir}".format(repo_dir=REPO_DIR)
)
sys.path.insert(0, REPO_DIR)
from mtanalyze.minebest import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
