#!/usr/bin/env python
from __future__ import print_function
import sys
import re
import os

from find_mtanalyze import mtanalyze
# ^ also works for submodules since changes sys.path

from mtanalyze.minebest import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
